const dummyData = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    profileImage: "https://example.com/john.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    profileImage: "https://example.com/jane.jpg",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob@example.com",
    phone: "555-123-4567",
    profileImage: "https://example.com/bob.jpg",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice@example.com",
    phone: "111-222-3333",
    profileImage: "https://example.com/alice.jpg",
  },
  {
    id: 5,
    name: "Ella Wilson",
    email: "ella@example.com",
    phone: "333-111-5555",
    profileImage: "https://example.com/ella.jpg",
  },
  {
    id: 6,
    name: "Chris Evans",
    email: "chris@example.com",
    phone: "444-777-8888",
    profileImage: "https://example.com/chris.jpg",
  },
  {
    id: 7,
    name: "Grace Kelly",
    email: "grace@example.com",
    phone: "555-444-2222",
    profileImage: "https://example.com/grace.jpg",
  },
  {
    id: 8,
    name: "Daniel White",
    email: "daniel@example.com",
    phone: "666-333-9999",
    profileImage: "https://example.com/daniel.jpg",
  },
  {
    id: 9,
    name: "Linda Green",
    email: "linda@example.com",
    phone: "777-222-4444",
    profileImage: "https://example.com/linda.jpg",
  },
  {
    id: 10,
    name: "Michael Jackson",
    email: "michael@example.com",
    phone: "888-111-7777",
    profileImage: "https://example.com/michael.jpg",
  },
  {
    id: 11,
    name: "Sophia Lee",
    email: "sophia@example.com",
    phone: "999-333-6666",
    profileImage: "https://example.com/sophia.jpg",
  },
  {
    id: 12,
    name: "Robert Taylor",
    email: "robert@example.com",
    phone: "111-777-8888",
    profileImage: "https://example.com/robert.jpg",
  },
  {
    id: 13,
    name: "Olivia Adams",
    email: "olivia@example.com",
    phone: "222-444-9999",
    profileImage: "https://example.com/olivia.jpg",
  },
  {
    id: 14,
    name: "William Hall",
    email: "william@example.com",
    phone: "333-555-6666",
    profileImage: "https://example.com/william.jpg",
  },
  {
    id: 15,
    name: "Ava Martin",
    email: "ava@example.com",
    phone: "444-777-8888",
    profileImage: "https://example.com/ava.jpg",
  },
];

export default dummyData;
